### ISSUE TITLE
Transfer this repository to JuliaCI

### ISSUE THREAD

**Issue by tkf** [JuliaPy/install-julia#1]
As discussed with @tpapp in [discourse](https://discourse.julialang.org/t/install-script-for-linux-for-use-in-container/19301), it would make sense to host repository in @JuliaCI.  Is it possible?

**Comment by StefanKarpinski** [comment]
@staticfloat, thoughts?

**Comment by stevengj** [comment]
Is there a better name for the repo?

**Comment by staticfloat** [comment]
I don't particularly care about the repo name.  `JuliaCI/install-julia` seems fine to me.

**Comment by tkf** [comment]
Names like `getjulia` and `julia-installer` also make sense, but I don't have any particular preference.

**Comment by staticfloat** [comment]
I actually have a bash script in my dotfiles called `getjulia` that does almost the same thing this bash script does.  ;)

**Comment by StefanKarpinski** [comment]
`fetch-julia`, `download-julia`?

**Comment by tpapp** [comment]
I would prefer the repo finding a permanent home (that I can link to) quickly to optimizing on the name. It would be useful to be more flexible with CI on Gitlab, cf https://gitlab.com/tkpapp/GitlabJuliaDemo.jl/issues/2 .

I am totally fine with `install-julia`, any of the above alterantives, or possibly `install-julia-binaries`.

**Comment by tpapp** [comment]
Friendly bump: can someone with commit rights to JuliaCI pick a repo name, or accept the transfer as is?

**Comment by stevengj** [comment]
I transferred it; it can be renamed under JuliaCI if desired.
